name: elmed219
dependencies:
  - python=3.8
  - pip
  - ipython
  - ipykernel
  - ipywidgets
  - jupyter
  - git
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::jupyterlab
  - pip:
    - pip >= 22
    - kaggle
    - pycaret
    - voila
    - scikit-learn>1.0